# Generated by Selenium IDE
import json
import time
from time import sleep
from selenium import webdriver
import pytest
from selenium.webdriver.common.by import By

class TestTestbaidu():
    def setup_method(self):
        # 浏览器复用
        # chrome_args = webdriver.ChromeOptions()
        # chrome_args.debugger_address = "127.0.0.1:9222"
        # self.driver = webdriver.Chrome(options=chrome_args)

        # cookie使用
        self.driver = webdriver.Chrome()
        self.driver.get('https://work.weixin.qq.com/wework_admin/loginpage_wx?from=myhome')
        time.sleep(15)
        cookies = self.driver.get_cookies()
        print(cookies)

    def teardown_method(self):
        self.driver.quit()

    def test_cookies(self):

        # 获取 cookie
        # self.driver.get('https://work.weixin.qq.com/wework_admin/loginpage_wx?from=myhome')
        # time.sleep(15)
        cookies = self.driver.get_cookies()
        print(cookies)
        with open("cookie.json", "w") as f:
            json.dump(cookies, f)

        # 读取cookie
        self.driver.delete_all_cookies()
        self.driver.get("https://work.weixin.qq.com/")
        with open("cookie.json", "r") as f:
            cookies = json.load(f)

        for cookie in cookies:
            self.driver.add_cookie(cookie)

        self.driver.get("https://work.weixin.qq.com/wework_admin/frame#")
        sleep(3)
        self.driver.find_element(By.XPATH, "//*[@id='menu_customer']").click()
        sleep(2)

        # 浏览器复用
        # self.driver.get("https://work.weixin.qq.com")
        # self.driver.find_element_by_class_name("index_top_operation_loginBtn").click()
        # self.driver.find_element_by_id("menu_customer").click()


if __name__ == '__main__':
    pytest.main(['-sv','test_demo.py'])

    # def test_testbaidu(self):
        # self.driver.get("https://work.weixin.qq.com/")
        # sleep(10)
        # self.driver.find_element(By.XPATH, "//*[@id='menu_contacts']").click()
        # self.driver.find_element(By.XPATH, '//*[@id="menu_customer"]').click()
        # self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        # self.driver.get("https://work.weixin.qq.com/wework_admin/frame")
        # sleep(3)
        # self.driver.find_element(By.XPATH, "//*[@id='menu_contacts']").click()







